/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    war
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Spring
    implementation("org.springframework:spring-context:5.3.16")

    // Spring data JPA
    implementation("org.springframework.data:spring-data-jpa:2.6.2")
    implementation("org.springframework:spring-orm:5.3.16")
    implementation("org.springframework:spring-jdbc:5.3.16")
    implementation("com.h2database:h2:2.1.210")
    implementation("org.hibernate:hibernate-core:5.6.7.Final")

    // Spring web mvc
    implementation("org.springframework:spring-webmvc:5.3.17")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.13.2")
    compileOnly("javax.servlet:javax.servlet-api:4.0.1")


    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
    testImplementation("javax.servlet:javax.servlet-api:4.0.1")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
