/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    // java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Spring
    implementation("org.springframework:spring-context:5.3.16")

    // Spring data JPA
    implementation("org.springframework.data:spring-data-jpa:2.6.2")
    implementation("org.springframework:spring-orm:5.3.16")
    implementation("org.springframework:spring-jdbc:5.3.16")
    implementation("com.h2database:h2:2.1.210")
    implementation("org.hibernate:hibernate-core:5.6.7.Final")

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")
}

application {
    // Define the main class for the application.
    mainClass.set("com.placetolearn.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
